version: '3.8'
services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27018:27017"  # Change this line to use a different port on the host
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
